//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Beadando_bmt3q9
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Rendeles_DBEntities : DbContext
    {
        public Rendeles_DBEntities()
            : base("name=Rendeles_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pizza_adatok> Pizza_adatok { get; set; }
        public virtual DbSet<Pizza_nev> Pizza_nev { get; set; }
        public virtual DbSet<Rendelesek> Rendeleseks { get; set; }
    }
}
