//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Beadando_bmt3q9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizza_adatok
    {
        public int Id { get; set; }
        public decimal kcal__szeletenkent_ { get; set; }
        public decimal zsir__szeletenkent_ { get; set; }
        public decimal szenhidrat__szeletenkent_ { get; set; }
        public decimal feherje__szeletenkent_ { get; set; }
        public int pizza_FK { get; set; }
    
        public virtual Pizza_nev Pizza_nev { get; set; }
    }
}
