//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Beadando_bmt3q9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizza_nev
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pizza_nev()
        {
            this.Pizza_adatok = new HashSet<Pizza_adatok>();
        }
    
        public int Id { get; set; }
        public string Nev { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pizza_adatok> Pizza_adatok { get; set; }
    }
}
