//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Beadando_bmt3q9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rendelesek
    {
        public int Id { get; set; }
        public int Hawaii_Pizza { get; set; }
        public int Pepperonis_Pizza { get; set; }
        public int Tenger_Gyumolcsei_Pizza { get; set; }
        public string Név { get; set; }
        public string Telfonszám { get; set; }
    }
}
